name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true

      - name: Show conda installation info
        run: |
          mamba info
          mamba list

      - name: Install requirements
        run: |
          mamba install --file=requirements-testing.txt
          pip install -r requirements.txt
          mamba list

      - name: Build and install package
        run: |
          pip install -e .

      - name: Test
        run: |
          python -c 'import barrier3d; print(barrier3d.__version__)'
          b3d --help
          b3d --version
          b3d plot --help
          b3d run --help
          b3d setup --help
          b3d show --help
          pytest -vvv
