name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          miniforge-version: latest

      - name: Install nox
        run: |
          pip install nox

      - name: Test
        run: |
          nox -s test

      - name: Test cli
        run: |
          nox -s test-cli

      - name: Test notebooks
        run: |
          nox -s test-notebooks

  test-with-v1:
    name: Test with original version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
          miniforge-variant: Mambaforge
          miniforge-version: latest

      - name: Install nox
        run: pip install nox

      - name: Test
        run: nox -s test-versions
